import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

async function seedBotpressApiAnalytics() {
  console.log('🌱 Starte Botpress API Analytics Seed-Prozess...');

  // Lösche vorhandene Analytics-Daten
  // @ts-ignore - Model könnte noch nicht im generierten Client sein
  await prisma.botpressApiAnalytics.deleteMany({});
  console.log('✅ Vorhandene Botpress API Analytics-Daten gelöscht');

  // Erstelle Demodaten basierend auf dem Schema
  const analyticsData = [
    {
      botId: 'bot_001',
      date: new Date('2025-11-10'),
      returningUsers: 5,
      newUsers: 2,
      sessions: 7,
      totalMessages: 85,
      userMessages: 48,
      botMessages: 37,
      events: 3,
      eventTypes: JSON.stringify({ session_start: 3 }),
      llmCalls: 55,
      llmErrors: 1,
      llmInputTokens: 120500,
      llmOutputTokens: 4500,
      llmLatencyMean: 2100.4,
      llmCostSum: 0.52011,
      llmCostMean: 0.00946,
      hourlyRecordsCount: 3,
      createdAt: new Date('2025-11-10T23:59:00'),
      syncDate: new Date('2025-11-10'),
    },
    {
      botId: 'bot_001',
      date: new Date('2025-11-09'),
      returningUsers: 3,
      newUsers: 1,
      sessions: 4,
      totalMessages: 42,
      userMessages: 20,
      botMessages: 22,
      events: 1,
      eventTypes: JSON.stringify({ state_expired: 1 }),
      llmCalls: 22,
      llmErrors: 0,
      llmInputTokens: 50220,
      llmOutputTokens: 2100,
      llmLatencyMean: 1850.2,
      llmCostSum: 0.19920,
      llmCostMean: 0.00905,
      hourlyRecordsCount: 1,
      createdAt: new Date('2025-11-09T23:50:00'),
      syncDate: new Date('2025-11-09'),
    },
    {
      botId: 'bot_002',
      date: new Date('2025-11-11'),
      returningUsers: 7,
      newUsers: 3,
      sessions: 10,
      totalMessages: 110,
      userMessages: 60,
      botMessages: 50,
      events: 4,
      eventTypes: JSON.stringify({ button_click: 2, flow_end: 2 }),
      llmCalls: 70,
      llmErrors: 2,
      llmInputTokens: 180340,
      llmOutputTokens: 6020,
      llmLatencyMean: 2540.8,
      llmCostSum: 0.64055,
      llmCostMean: 0.00915,
      hourlyRecordsCount: 4,
      createdAt: new Date('2025-11-11T20:20:00'),
      syncDate: new Date('2025-11-11'),
    },
    {
      botId: 'bot_003',
      date: new Date('2025-11-08'),
      returningUsers: 2,
      newUsers: 0,
      sessions: 2,
      totalMessages: 18,
      userMessages: 9,
      botMessages: 9,
      events: 1,
      eventTypes: JSON.stringify({ unknown_intent: 1 }),
      llmCalls: 12,
      llmErrors: 0,
      llmInputTokens: 14000,
      llmOutputTokens: 900,
      llmLatencyMean: 1750.6,
      llmCostSum: 0.08810,
      llmCostMean: 0.00734,
      hourlyRecordsCount: 1,
      createdAt: new Date('2025-11-08T18:10:00'),
      syncDate: new Date('2025-11-08'),
    },
    {
      botId: 'bot_003',
      date: new Date('2025-11-12'),
      returningUsers: 4,
      newUsers: 1,
      sessions: 5,
      totalMessages: 51,
      userMessages: 25,
      botMessages: 26,
      events: 2,
      eventTypes: JSON.stringify({ flow_start: 1, flow_end: 1 }),
      llmCalls: 30,
      llmErrors: 1,
      llmInputTokens: 72000,
      llmOutputTokens: 2800,
      llmLatencyMean: 1980.5,
      llmCostSum: 0.21095,
      llmCostMean: 0.00703,
      hourlyRecordsCount: 2,
      createdAt: new Date('2025-11-12T21:05:00'),
      syncDate: new Date('2025-11-12'),
    },
    {
      botId: 'bot_001',
      date: new Date('2025-11-13'),
      returningUsers: 8,
      newUsers: 4,
      sessions: 12,
      totalMessages: 145,
      userMessages: 78,
      botMessages: 67,
      events: 5,
      eventTypes: JSON.stringify({ session_start: 3, button_click: 2 }),
      llmCalls: 95,
      llmErrors: 0,
      llmInputTokens: 210000,
      llmOutputTokens: 8500,
      llmLatencyMean: 2200.3,
      llmCostSum: 0.85000,
      llmCostMean: 0.00895,
      hourlyRecordsCount: 5,
      createdAt: new Date('2025-11-13T15:30:00'),
      syncDate: new Date('2025-11-13'),
    },
    {
      botId: 'bot_002',
      date: new Date('2025-11-13'),
      returningUsers: 6,
      newUsers: 2,
      sessions: 8,
      totalMessages: 92,
      userMessages: 48,
      botMessages: 44,
      events: 3,
      eventTypes: JSON.stringify({ flow_start: 2, flow_end: 1 }),
      llmCalls: 58,
      llmErrors: 1,
      llmInputTokens: 145000,
      llmOutputTokens: 5200,
      llmLatencyMean: 1950.7,
      llmCostSum: 0.52000,
      llmCostMean: 0.00897,
      hourlyRecordsCount: 3,
      createdAt: new Date('2025-11-13T18:15:00'),
      syncDate: new Date('2025-11-13'),
    },
    {
      botId: 'bot_004',
      date: new Date('2025-11-14'),
      returningUsers: 12,
      newUsers: 5,
      sessions: 17,
      totalMessages: 198,
      userMessages: 105,
      botMessages: 93,
      events: 7,
      eventTypes: JSON.stringify({ session_start: 4, button_click: 3 }),
      llmCalls: 125,
      llmErrors: 2,
      llmInputTokens: 285000,
      llmOutputTokens: 12000,
      llmLatencyMean: 2400.5,
      llmCostSum: 1.15000,
      llmCostMean: 0.00920,
      hourlyRecordsCount: 7,
      createdAt: new Date('2025-11-14T12:45:00'),
      syncDate: new Date('2025-11-14'),
    },
    {
      botId: 'bot_001',
      date: new Date('2025-11-14'),
      returningUsers: 9,
      newUsers: 3,
      sessions: 12,
      totalMessages: 132,
      userMessages: 68,
      botMessages: 64,
      events: 4,
      eventTypes: JSON.stringify({ flow_start: 2, flow_end: 2 }),
      llmCalls: 82,
      llmErrors: 0,
      llmInputTokens: 195000,
      llmOutputTokens: 7200,
      llmLatencyMean: 2100.2,
      llmCostSum: 0.75000,
      llmCostMean: 0.00915,
      hourlyRecordsCount: 4,
      createdAt: new Date('2025-11-14T19:20:00'),
      syncDate: new Date('2025-11-14'),
    },
    {
      botId: 'bot_003',
      date: new Date('2025-11-15'),
      returningUsers: 5,
      newUsers: 2,
      sessions: 7,
      totalMessages: 78,
      userMessages: 40,
      botMessages: 38,
      events: 2,
      eventTypes: JSON.stringify({ session_start: 1, unknown_intent: 1 }),
      llmCalls: 48,
      llmErrors: 1,
      llmInputTokens: 115000,
      llmOutputTokens: 4500,
      llmLatencyMean: 1850.8,
      llmCostSum: 0.42000,
      llmCostMean: 0.00875,
      hourlyRecordsCount: 2,
      createdAt: new Date('2025-11-15T10:30:00'),
      syncDate: new Date('2025-11-15'),
    },
    {
      botId: 'bot_002',
      date: new Date('2025-11-15'),
      returningUsers: 11,
      newUsers: 6,
      sessions: 17,
      totalMessages: 205,
      userMessages: 110,
      botMessages: 95,
      events: 8,
      eventTypes: JSON.stringify({ session_start: 5, button_click: 3 }),
      llmCalls: 135,
      llmErrors: 3,
      llmInputTokens: 310000,
      llmOutputTokens: 13500,
      llmLatencyMean: 2650.4,
      llmCostSum: 1.25000,
      llmCostMean: 0.00926,
      hourlyRecordsCount: 8,
      createdAt: new Date('2025-11-15T16:00:00'),
      syncDate: new Date('2025-11-15'),
    },
    {
      botId: 'bot_005',
      date: new Date('2025-11-16'),
      returningUsers: 3,
      newUsers: 1,
      sessions: 4,
      totalMessages: 45,
      userMessages: 22,
      botMessages: 23,
      events: 1,
      eventTypes: JSON.stringify({ flow_end: 1 }),
      llmCalls: 28,
      llmErrors: 0,
      llmInputTokens: 68000,
      llmOutputTokens: 2800,
      llmLatencyMean: 1750.3,
      llmCostSum: 0.28000,
      llmCostMean: 0.01000,
      hourlyRecordsCount: 1,
      createdAt: new Date('2025-11-16T14:15:00'),
      syncDate: new Date('2025-11-16'),
    },
    {
      botId: 'bot_001',
      date: new Date('2025-11-16'),
      returningUsers: 15,
      newUsers: 7,
      sessions: 22,
      totalMessages: 265,
      userMessages: 140,
      botMessages: 125,
      events: 10,
      eventTypes: JSON.stringify({ session_start: 6, button_click: 4 }),
      llmCalls: 175,
      llmErrors: 1,
      llmInputTokens: 400000,
      llmOutputTokens: 18000,
      llmLatencyMean: 2300.6,
      llmCostSum: 1.60000,
      llmCostMean: 0.00914,
      hourlyRecordsCount: 10,
      createdAt: new Date('2025-11-16T20:45:00'),
      syncDate: new Date('2025-11-16'),
    },
    {
      botId: 'bot_004',
      date: new Date('2025-11-17'),
      returningUsers: 7,
      newUsers: 3,
      sessions: 10,
      totalMessages: 118,
      userMessages: 62,
      botMessages: 56,
      events: 5,
      eventTypes: JSON.stringify({ flow_start: 3, flow_end: 2 }),
      llmCalls: 75,
      llmErrors: 2,
      llmInputTokens: 180000,
      llmOutputTokens: 7500,
      llmLatencyMean: 2050.9,
      llmCostSum: 0.68000,
      llmCostMean: 0.00907,
      hourlyRecordsCount: 5,
      createdAt: new Date('2025-11-17T11:20:00'),
      syncDate: new Date('2025-11-17'),
    },
    {
      botId: 'bot_002',
      date: new Date('2025-11-17'),
      returningUsers: 10,
      newUsers: 4,
      sessions: 14,
      totalMessages: 168,
      userMessages: 88,
      botMessages: 80,
      events: 6,
      eventTypes: JSON.stringify({ session_start: 4, button_click: 2 }),
      llmCalls: 108,
      llmErrors: 0,
      llmInputTokens: 250000,
      llmOutputTokens: 11000,
      llmLatencyMean: 2150.2,
      llmCostSum: 0.98000,
      llmCostMean: 0.00907,
      hourlyRecordsCount: 6,
      createdAt: new Date('2025-11-17T17:30:00'),
      syncDate: new Date('2025-11-17'),
    },
    {
      botId: 'bot_003',
      date: new Date('2025-11-18'),
      returningUsers: 6,
      newUsers: 2,
      sessions: 8,
      totalMessages: 95,
      userMessages: 48,
      botMessages: 47,
      events: 3,
      eventTypes: JSON.stringify({ flow_start: 2, unknown_intent: 1 }),
      llmCalls: 60,
      llmErrors: 1,
      llmInputTokens: 145000,
      llmOutputTokens: 5800,
      llmLatencyMean: 1920.5,
      llmCostSum: 0.54000,
      llmCostMean: 0.00900,
      hourlyRecordsCount: 3,
      createdAt: new Date('2025-11-18T13:00:00'),
      syncDate: new Date('2025-11-18'),
    },
    {
      botId: 'bot_005',
      date: new Date('2025-11-18'),
      returningUsers: 4,
      newUsers: 1,
      sessions: 5,
      totalMessages: 58,
      userMessages: 30,
      botMessages: 28,
      events: 2,
      eventTypes: JSON.stringify({ session_start: 1, flow_end: 1 }),
      llmCalls: 36,
      llmErrors: 0,
      llmInputTokens: 85000,
      llmOutputTokens: 3600,
      llmLatencyMean: 1800.4,
      llmCostSum: 0.36000,
      llmCostMean: 0.01000,
      hourlyRecordsCount: 2,
      createdAt: new Date('2025-11-18T15:45:00'),
      syncDate: new Date('2025-11-18'),
    },
    {
      botId: 'bot_001',
      date: new Date('2025-11-19'),
      returningUsers: 13,
      newUsers: 5,
      sessions: 18,
      totalMessages: 215,
      userMessages: 115,
      botMessages: 100,
      events: 9,
      eventTypes: JSON.stringify({ session_start: 5, button_click: 4 }),
      llmCalls: 142,
      llmErrors: 2,
      llmInputTokens: 325000,
      llmOutputTokens: 14500,
      llmLatencyMean: 2450.8,
      llmCostSum: 1.32000,
      llmCostMean: 0.00930,
      hourlyRecordsCount: 9,
      createdAt: new Date('2025-11-19T14:20:00'),
      syncDate: new Date('2025-11-19'),
    },
    {
      botId: 'bot_004',
      date: new Date('2025-11-19'),
      returningUsers: 8,
      newUsers: 3,
      sessions: 11,
      totalMessages: 128,
      userMessages: 68,
      botMessages: 60,
      events: 4,
      eventTypes: JSON.stringify({ flow_start: 2, flow_end: 2 }),
      llmCalls: 82,
      llmErrors: 1,
      llmInputTokens: 195000,
      llmOutputTokens: 8200,
      llmLatencyMean: 2100.6,
      llmCostSum: 0.75000,
      llmCostMean: 0.00915,
      hourlyRecordsCount: 4,
      createdAt: new Date('2025-11-19T19:10:00'),
      syncDate: new Date('2025-11-19'),
    },
    {
      botId: 'bot_002',
      date: new Date('2025-11-20'),
      returningUsers: 14,
      newUsers: 8,
      sessions: 22,
      totalMessages: 278,
      userMessages: 148,
      botMessages: 130,
      events: 11,
      eventTypes: JSON.stringify({ session_start: 7, button_click: 4 }),
      llmCalls: 185,
      llmErrors: 3,
      llmInputTokens: 425000,
      llmOutputTokens: 19500,
      llmLatencyMean: 2750.3,
      llmCostSum: 1.75000,
      llmCostMean: 0.00946,
      hourlyRecordsCount: 11,
      createdAt: new Date('2025-11-20T16:30:00'),
      syncDate: new Date('2025-11-20'),
    },
  ];

  // Füge Daten zur Datenbank hinzu
  for (const data of analyticsData) {
    // @ts-ignore - Model könnte noch nicht im generierten Client sein
    await prisma.botpressApiAnalytics.create({
      data,
    });
    console.log(`✅ Bot ${data.botId} - ${data.date.toISOString().split('T')[0]} Daten erstellt`);
  }

  console.log('🎉 Seed-Prozess abgeschlossen!');
}

async function seedChatbotAnalytics() {
  console.log('🌱 Starte ChatbotAnalytics Seed-Prozess...');

  // Lösche vorhandene ChatbotAnalytics-Daten
  // @ts-ignore
  await prisma.chatbotAnalytics.deleteMany({});
  console.log('✅ Vorhandene ChatbotAnalytics-Daten gelöscht');

  // Erstelle Demodaten für Konversationen
  const conversationsData = [
    {
      conversationId: 'conv_001',
      date: new Date('2025-11-10'),
      integration: 'Webchat',
      totalMessages: 12,
      userMessages: 6,
      botMessages: 6,
      avgMessageLength: 45.3,
      sentiment: 'positive',
      keywords: JSON.stringify(['angebot', 'support', 'kontakt']),
      tags: JSON.stringify(['sales', 'lead']),
      summary: 'User asked for product pricing and contact info',
      personalContactRequested: 1,
      requestedContactChannel: 'Telefon',
      customerType: 'Geschäftskunden',
      customerRegion: '80331',
      createdAt: new Date('2025-11-10T14:22:00'),
    },
    {
      conversationId: 'conv_002',
      date: new Date('2025-11-09'),
      integration: 'WhatsApp',
      totalMessages: 8,
      userMessages: 5,
      botMessages: 3,
      avgMessageLength: 38.5,
      sentiment: 'neutral',
      keywords: JSON.stringify(['hilfe', 'konto', 'login']),
      tags: JSON.stringify(['support', 'authentication']),
      summary: 'User requested help with login issue',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Privatkunden',
      customerRegion: '10115',
      createdAt: new Date('2025-11-09T09:05:00'),
    },
    {
      conversationId: 'conv_003',
      date: new Date('2025-11-11'),
      integration: 'Slack',
      totalMessages: 15,
      userMessages: 7,
      botMessages: 8,
      avgMessageLength: 52.7,
      sentiment: 'positive',
      keywords: JSON.stringify(['termin', 'beratung', 'angebot']),
      tags: JSON.stringify(['consulting', 'lead']),
      summary: 'Conversation about scheduling a consultation',
      personalContactRequested: 1,
      requestedContactChannel: 'E-Mail',
      customerType: 'Geschäftskunden',
      customerRegion: '20095',
      createdAt: new Date('2025-11-11T11:45:00'),
    },
    {
      conversationId: 'conv_004',
      date: new Date('2025-11-08'),
      integration: 'Webchat',
      totalMessages: 10,
      userMessages: 5,
      botMessages: 5,
      avgMessageLength: 30.9,
      sentiment: 'negative',
      keywords: JSON.stringify(['problem', 'lieferung', 'beschwerde']),
      tags: JSON.stringify(['complaint']),
      summary: 'User expressed dissatisfaction about delivery delay',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Privatkunden',
      customerRegion: '50667',
      createdAt: new Date('2025-11-08T17:20:00'),
    },
    {
      conversationId: 'conv_005',
      date: new Date('2025-11-11'),
      integration: 'E-Mail',
      totalMessages: 6,
      userMessages: 3,
      botMessages: 3,
      avgMessageLength: 40.1,
      sentiment: 'neutral',
      keywords: JSON.stringify(['rechnung', 'status', 'zahlung']),
      tags: JSON.stringify(['billing', 'info-request']),
      summary: 'User asked for invoice payment status',
      personalContactRequested: 1,
      requestedContactChannel: 'Beides',
      customerType: 'Geschäftskunden',
      customerRegion: '70173',
      createdAt: new Date('2025-11-11T10:10:00'),
    },
    {
      conversationId: 'conv_006',
      date: new Date('2025-11-12'),
      integration: 'Webchat',
      totalMessages: 14,
      userMessages: 7,
      botMessages: 7,
      avgMessageLength: 48.2,
      sentiment: 'positive',
      keywords: JSON.stringify(['produkt', 'preis', 'bestellung']),
      tags: JSON.stringify(['sales', 'order']),
      summary: 'Customer inquired about product pricing and placed an order',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Privatkunden',
      customerRegion: '80331',
      createdAt: new Date('2025-11-12T09:30:00'),
    },
    {
      conversationId: 'conv_007',
      date: new Date('2025-11-12'),
      integration: 'WhatsApp',
      totalMessages: 9,
      userMessages: 5,
      botMessages: 4,
      avgMessageLength: 35.8,
      sentiment: 'positive',
      keywords: JSON.stringify(['danke', 'zufrieden', 'empfehlung']),
      tags: JSON.stringify(['feedback', 'positive']),
      summary: 'User expressed satisfaction and recommended the service',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Privatkunden',
      customerRegion: '10115',
      createdAt: new Date('2025-11-12T14:20:00'),
    },
    {
      conversationId: 'conv_008',
      date: new Date('2025-11-13'),
      integration: 'Slack',
      totalMessages: 18,
      userMessages: 9,
      botMessages: 9,
      avgMessageLength: 55.4,
      sentiment: 'neutral',
      keywords: JSON.stringify(['integration', 'api', 'dokumentation']),
      tags: JSON.stringify(['technical', 'support']),
      summary: 'Technical discussion about API integration and documentation',
      personalContactRequested: 1,
      requestedContactChannel: 'E-Mail',
      customerType: 'Geschäftskunden',
      customerRegion: '20095',
      createdAt: new Date('2025-11-13T11:15:00'),
    },
    {
      conversationId: 'conv_009',
      date: new Date('2025-11-13'),
      integration: 'Webchat',
      totalMessages: 11,
      userMessages: 6,
      botMessages: 5,
      avgMessageLength: 42.6,
      sentiment: 'negative',
      keywords: JSON.stringify(['rückgabe', 'reklamation', 'unzufrieden']),
      tags: JSON.stringify(['complaint', 'return']),
      summary: 'Customer requested return and expressed dissatisfaction',
      personalContactRequested: 1,
      requestedContactChannel: 'Telefon',
      customerType: 'Privatkunden',
      customerRegion: '50667',
      createdAt: new Date('2025-11-13T16:45:00'),
    },
    {
      conversationId: 'conv_010',
      date: new Date('2025-11-14'),
      integration: 'E-Mail',
      totalMessages: 7,
      userMessages: 4,
      botMessages: 3,
      avgMessageLength: 38.9,
      sentiment: 'positive',
      keywords: JSON.stringify(['angebot', 'interesse', 'kontakt']),
      tags: JSON.stringify(['lead', 'sales']),
      summary: 'User showed interest in product offer and requested contact',
      personalContactRequested: 1,
      requestedContactChannel: 'E-Mail',
      customerType: 'Geschäftskunden',
      customerRegion: '70173',
      createdAt: new Date('2025-11-14T10:00:00'),
    },
    {
      conversationId: 'conv_011',
      date: new Date('2025-11-14'),
      integration: 'WhatsApp',
      totalMessages: 13,
      userMessages: 7,
      botMessages: 6,
      avgMessageLength: 44.3,
      sentiment: 'neutral',
      keywords: JSON.stringify(['lieferung', 'versand', 'tracking']),
      tags: JSON.stringify(['shipping', 'info-request']),
      summary: 'Customer asked about delivery status and tracking information',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Privatkunden',
      customerRegion: '80331',
      createdAt: new Date('2025-11-14T13:30:00'),
    },
    {
      conversationId: 'conv_012',
      date: new Date('2025-11-15'),
      integration: 'Webchat',
      totalMessages: 16,
      userMessages: 8,
      botMessages: 8,
      avgMessageLength: 50.1,
      sentiment: 'positive',
      keywords: JSON.stringify(['beratung', 'termin', 'meeting']),
      tags: JSON.stringify(['consulting', 'appointment']),
      summary: 'User scheduled a consultation meeting',
      personalContactRequested: 1,
      requestedContactChannel: 'Beides',
      customerType: 'Geschäftskunden',
      customerRegion: '20095',
      createdAt: new Date('2025-11-15T09:20:00'),
    },
    {
      conversationId: 'conv_013',
      date: new Date('2025-11-15'),
      integration: 'Slack',
      totalMessages: 10,
      userMessages: 5,
      botMessages: 5,
      avgMessageLength: 36.7,
      sentiment: 'neutral',
      keywords: JSON.stringify(['konto', 'einstellungen', 'profil']),
      tags: JSON.stringify(['account', 'settings']),
      summary: 'User asked about account settings and profile management',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Privatkunden',
      customerRegion: '10115',
      createdAt: new Date('2025-11-15T15:10:00'),
    },
    {
      conversationId: 'conv_014',
      date: new Date('2025-11-16'),
      integration: 'E-Mail',
      totalMessages: 8,
      userMessages: 4,
      botMessages: 4,
      avgMessageLength: 41.5,
      sentiment: 'positive',
      keywords: JSON.stringify(['vorteil', 'funktion', 'features']),
      tags: JSON.stringify(['product-info', 'sales']),
      summary: 'Customer inquired about product features and advantages',
      personalContactRequested: 1,
      requestedContactChannel: 'Telefon',
      customerType: 'Geschäftskunden',
      customerRegion: '70173',
      createdAt: new Date('2025-11-16T11:45:00'),
    },
    {
      conversationId: 'conv_015',
      date: new Date('2025-11-16'),
      integration: 'Webchat',
      totalMessages: 12,
      userMessages: 6,
      botMessages: 6,
      avgMessageLength: 46.8,
      sentiment: 'negative',
      keywords: JSON.stringify(['fehler', 'problem', 'support']),
      tags: JSON.stringify(['bug', 'support']),
      summary: 'User reported a technical issue and requested support',
      personalContactRequested: 1,
      requestedContactChannel: 'E-Mail',
      customerType: 'Privatkunden',
      customerRegion: '50667',
      createdAt: new Date('2025-11-16T17:20:00'),
    },
    {
      conversationId: 'conv_016',
      date: new Date('2025-11-17'),
      integration: 'WhatsApp',
      totalMessages: 15,
      userMessages: 8,
      botMessages: 7,
      avgMessageLength: 52.3,
      sentiment: 'positive',
      keywords: JSON.stringify(['kauf', 'bestellung', 'zahlung']),
      tags: JSON.stringify(['order', 'payment']),
      summary: 'Customer completed a purchase and payment process',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Privatkunden',
      customerRegion: '80331',
      createdAt: new Date('2025-11-17T10:15:00'),
    },
    {
      conversationId: 'conv_017',
      date: new Date('2025-11-17'),
      integration: 'Slack',
      totalMessages: 19,
      userMessages: 10,
      botMessages: 9,
      avgMessageLength: 58.7,
      sentiment: 'neutral',
      keywords: JSON.stringify(['implementierung', 'setup', 'konfiguration']),
      tags: JSON.stringify(['technical', 'implementation']),
      summary: 'Technical discussion about implementation and configuration setup',
      personalContactRequested: 1,
      requestedContactChannel: 'Beides',
      customerType: 'Geschäftskunden',
      customerRegion: '20095',
      createdAt: new Date('2025-11-17T14:30:00'),
    },
    {
      conversationId: 'conv_018',
      date: new Date('2025-11-18'),
      integration: 'Webchat',
      totalMessages: 9,
      userMessages: 5,
      botMessages: 4,
      avgMessageLength: 39.2,
      sentiment: 'positive',
      keywords: JSON.stringify(['empfehlung', 'bewertung', 'feedback']),
      tags: JSON.stringify(['feedback', 'review']),
      summary: 'User provided positive feedback and recommendation',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Privatkunden',
      customerRegion: '10115',
      createdAt: new Date('2025-11-18T12:00:00'),
    },
    {
      conversationId: 'conv_019',
      date: new Date('2025-11-18'),
      integration: 'E-Mail',
      totalMessages: 6,
      userMessages: 3,
      botMessages: 3,
      avgMessageLength: 37.4,
      sentiment: 'neutral',
      keywords: JSON.stringify(['frage', 'information', 'auskunft']),
      tags: JSON.stringify(['info-request', 'general']),
      summary: 'General information request from customer',
      personalContactRequested: 0,
      requestedContactChannel: null,
      customerType: 'Geschäftskunden',
      customerRegion: '70173',
      createdAt: new Date('2025-11-18T16:25:00'),
    },
    {
      conversationId: 'conv_020',
      date: new Date('2025-11-19'),
      integration: 'WhatsApp',
      totalMessages: 17,
      userMessages: 9,
      botMessages: 8,
      avgMessageLength: 54.1,
      sentiment: 'positive',
      keywords: JSON.stringify(['angebot', 'rabatt', 'aktion']),
      tags: JSON.stringify(['sales', 'promotion']),
      summary: 'Customer inquired about special offers and discounts',
      personalContactRequested: 1,
      requestedContactChannel: 'Telefon',
      customerType: 'Privatkunden',
      customerRegion: '80331',
      createdAt: new Date('2025-11-19T08:45:00'),
    },
  ];

  // Füge Daten zur Datenbank hinzu
  for (const data of conversationsData) {
    const {
      botId = 'demo-bot',
      createdAt,
      syncDate,
      ...rest
    } = data as Record<string, any>;

    const payload = {
      botId,
      syncDate: syncDate ?? data.date,
      ...rest,
    } as Prisma.ChatbotAnalyticsCreateInput;

    await prisma.chatbotAnalytics.create({
      data: payload,
    });
    console.log(`✅ ${data.conversationId} Daten erstellt`);
  }

  console.log('🎉 ChatbotAnalytics Seed-Prozess abgeschlossen!');
}

async function main() {
  await seedBotpressApiAnalytics();
  await seedChatbotAnalytics();
}

main()
  .catch((e) => {
    console.error('❌ Fehler beim Seed-Prozess:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

